import { useNavigate } from "react-router-dom";
import solarBatteryBlog from "../../assets/images/blogThree.png";
import sunKing from "../../assets/images/sunKingBg.png";
import lumos from "../../assets/images/lumos.png";
import solynta from "../../assets/images/solynta.png";
import Button from "../../components/ButtonComponent";

import "./blogs.css";

function SolarBatteryBlog() {
  const navigate = useNavigate();
  return (
    <>
      <div className="blog__container relative">
        <div className="fixed top-[20px] left-[3rem] z-10 flex items-center rounded-full bg-[#3383ecf1] shadow-lg">
          <i
            onClick={() => navigate("/")}
            className="bx bx-chevron-left cursor-pointer rounded text-[40px] text-[#ffffff]"
          ></i>
        </div>
       <div className="relative h-[620px] w-full">
  <img
    className="h-full w-full object-cover brightness-75"
    src={solarBatteryBlog}
    alt="Solar Battery Blog"
  />
  <div className="absolute inset-0 bg-black/20"></div>
</div>


        <div className="absolute bottom-[4rem] left-[3rem]">
          <h3 className="text-[44px]">
            What's the Right Solar Panel for Your Home?
          </h3>
        </div>
      </div>

      <div className="blog__text__container mx-auto mt-[2rem] mb-[4rem] w-full max-w-[1200px] p-2">
        <p>
          Switching to solar energy is a great way to reduce electricity costs
          and gain energy independence. But to keep your home powered at night
          or during cloudy days, you'll need solar batteries. The big question
          is:{" "}
          <span classNmae="font-semiBold text-[#2266DE]">
            {" "}
            How many batteries do you actually need?
          </span>
        </p>

        <ol className="ml-5 flex list-decimal flex-col gap-8 text-[#2266DE]">
          <li>
            Understanding How Solar Batteries Work
            <div className="mt-5 text-black">
              <p>
                Solar batteries store excess energy generated by your solar
                panels during the day so you can use it when the sun isn’t
                shining. The number of batteries you need depends on:
              </p>
              <p>✅ Your daily energy consumption (in kilowatt-hours, kWh).</p>
              <p>
                ✅ The size of your solar system and how much power it
                generates.
              </p>
              <p>
                ✅ Whether you want partial backup (for essential appliances) or
                full backup (to power your entire home).
              </p>
            </div>
          </li>

          <li>
            Calculating How Many Batteries You Need
            <div className="mt-5 text-black">
              <p>
                To find out how many solar batteries your home needs, follow
                these steps:
              </p>
              <p>
                🔹 Step 1: Check Your Daily Energy Usage Look at your
                electricity bill to find your monthly kWh usage. Divide by 30 to
                get your daily consumption.
              </p>
              <p>
                💡 Example: If your home uses 600 kWh per month, your daily
                usage is:{" "}
              </p>
              <p>👉 600 ÷ 30 = 20 kWh per day</p>
              <p>🔹 Step 2: Consider Your Backup Needs</p>
              <ul className="mt-2 ml-5 list-disc">
                <li>
                  Partial Backup: If you only want to power essential appliances
                  like lights, fans, and refrigerators, you may only need 30-50%
                  of your total energy storage.
                </li>
                <li>
                  Full Backup: If you want your entire home to run on stored
                  energy, you'll need 100% of your daily consumption in battery
                  storage.
                </li>
              </ul>
            </div>
          </li>

          <li>
            Choosing the Right Battery Size
            <div className="mt-5 text-black">
              <p>
                Solar batteries come in different capacities, usually measured
                in kilowatt-hours (kWh). Common sizes include:
              </p>
              <ul className="mt-2 ml-5 list-disc">
                <li>
                  5 kWh battery - Suitable for small homes or partial backup.
                </li>
                <li>
                  10 kWh battery - Ideal for medium-sized homes with moderate
                  energy use.
                </li>
                <li>15-20 kWh battery - Best for full-home backup.</li>
              </ul>
              <p>💡 Example Calculation:</p>
              <p>
                If your home consumes 20 kWh per day, and each battery stores 5
                kWh, you would need:
              </p>
              <p> 👉 20 ÷ 5 = 4 batteries for full backup.</p>
              <p> 👉 2 batteries for partial backup (~50% power supply).</p>
            </div>
          </li>

          <li>
            Extra Factors to Consider
            <div className="mt-5 text-black">
              <ul className="mt-2 ml-5 list-disc">
                <li className="mt-8">
                  📌 Battery Type:
                  <div className="text-black">
                    <ul className="mt-2 ml-5 list-disc">
                      <li>
                        Lithium-ion batteries (e.g., Tesla Powerwall) are
                        long-lasting and efficient.
                      </li>
                      <li>
                        Lead-acid batteries are cheaper but require frequent
                        maintenance.
                      </li>
                    </ul>
                  </div>
                </li>
                <li className="mt-8">
                  📌 Battery Depth of Discharge (DoD):
                  <div className="text-black">
                    <ul className="mt-2 ml-5 list-disc">
                      <li>
                        Most batteries cannot be drained completely. For
                        example, if a battery has a 90% DoD, only 4.5 kWh of a 5
                        kWh battery is usable.
                      </li>
                    </ul>
                  </div>
                </li>
                <li className="mt-8">
                  📌 Number of Backup Hours:
                  <div className="text-black">
                    <ul className="mt-2 ml-5 list-disc">
                      <li>
                        If you want 8 hours of backup, calculate how many kWh
                        you need per hour and multiply by 8.
                      </li>
                    </ul>
                  </div>
                </li>
                <li className="mt-8">
                  📌 Solar Panel Size & Sunlight Exposure:
                  <div className="text-black">
                    <ul className="mt-2 ml-5 list-disc">
                      <li>
                        If your solar panels generate enough energy to recharge
                        batteries daily, you may need fewer batteries.
                      </li>
                    </ul>
                  </div>
                </li>
              </ul>
            </div>
          </li>

          <li >
            Conclusion - How Many Batteries Do You Really Need?
            <div className="text-black">
              <p>
                🔆 For essential backup (lights, fridge, fans) - 1 to 2
                batteries (5-10 kWh)
              </p>
              <p>
                🔆 For partial home backup (some appliances) - 2 to 3 batteries
                (10-15 kWh)
              </p>
              <p>🔆 For full home backup - 4+ batteries (20 kWh or more)</p>
              <p>
                🔋 Want to find out exactly how many batteries you need? Try our{" "}
                <span
                  className="text-underline"
                  onClick={() => navigate("/assessment-tool")}
                >
                  Solar Battery Calculator
                </span>{" "}
                to get personalized recommendations! 🚀
              </p>
            </div>
          </li>
        </ol>

        <div>
          <h3 className="mt-5 text-[20px] font-semibold text-[#2266DE]">
            Final Thoughts - Is Solar Worth It?
          </h3>

          <div className="mt-5 text-black">
            <p>
              YES! With long-term savings, reliable power, and environmental
              benefits, solar is one of the best investments you can make.
              Whether for your home or business, every kWh you generate reduces
              your reliance on expensive electricity.
            </p>

            <p>
              👉 Curious to know your exact savings? Use our Solar Savings
              Calculator to find out today! 🌞
            </p>
          </div>
        </div>

        {/* Top Vendors */}
        <div className="p-[5rem_2rem]">
          <h2 className="text-primary-500 mb-4 text-[32px] font-semibold">
            Our Vendors
          </h2>
          <div className="flex flex-col md:flex-row items-center justify-center gap-[124px]">
            <img src={lumos} alt="" />
            <img src={sunKing} alt="" />
            <img src={solynta} alt="" />
          </div>
          <div className="m-[2rem_0] flex items-end justify-end">
            <Button type="secondary" link="#">
              View all
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}

export default SolarBatteryBlog;
